# Generated by Django 3.0.3 on 2020-02-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.AddField(
            model_name='item',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='menu.Item'),
        ),
    ]
