# Generated by Django 3.0.3 on 2020-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200218_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='child',
        ),
        migrations.AddField(
            model_name='item',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='_item_child_+', to='menu.Item'),
        ),
    ]
