# Generated by Django 3.0.3 on 2020-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.AddField(
            model_name='item',
            name='nesting_level',
            field=models.IntegerField(default=0, verbose_name='Уровень вложенности'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='main_item',
        ),
        migrations.AddField(
            model_name='menu',
            name='main_item',
            field=models.ManyToManyField(related_name='menu', to='menu.Item'),
        ),
    ]
