# Generated by Django 3.0.3 on 2020-02-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_item_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nesting_level'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='main_item',
            new_name='items',
        ),
    ]
