# Generated by Django 3.0.3 on 2020-02-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200221_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='items',
            new_name='menu_items',
        ),
    ]
